type Audience = 'PLATFORM' | 'ORGANIZATION' | 'BOTH';
type Scope = 'OWN' | 'BRANCH' | 'ORGANIZATION' | 'PLATFORM';
type RoleContext = 'PLATFORM' | 'ORGANIZATION';

export type ModuleSeed = {
  key: string;
  name: string;
  icon?: string;
  audience: Audience;
  sortOrder: number;
  submodules: Array<{
    key: string;
    name: string;
    route: string;
    permissionKey?: string;
    sortOrder: number;
  }>;
};

export type PermissionSeed = {
  key: string;
  name: string;
  description: string;
  moduleKey: string;
  submoduleKey?: string;
  scope: Scope;
  audience: Audience;
};

export type RoleSeed = {
  context: RoleContext;
  scopeKey: string;
  key: string;
  name: string;
  description: string;
  isSystem: boolean;
  permissionKeys: string[];
};

export const platformModules: ModuleSeed[] = [
  {
    key: 'platform',
    name: 'Superadmin',
    icon: 'shield',
    audience: 'PLATFORM',
    sortOrder: 10,
    submodules: [
      {
        key: 'organizations',
        name: 'Organizaciones',
        route: '/platform/organizaciones',
        permissionKey: 'platform.organizations.read',
        sortOrder: 10,
      },
      {
        key: 'global-users',
        name: 'Usuarios globales',
        route: '/platform/usuarios',
        permissionKey: 'platform.users.read',
        sortOrder: 20,
      },
      {
        key: 'roles',
        name: 'Roles base',
        route: '/platform/roles',
        permissionKey: 'platform.roles.read',
        sortOrder: 30,
      },
      {
        key: 'permissions',
        name: 'Permisos maestros',
        route: '/platform/permisos',
        permissionKey: 'platform.permissions.read',
        sortOrder: 40,
      },
      {
        key: 'modules',
        name: 'Modulos del sistema',
        route: '/platform/modulos',
        permissionKey: 'platform.modules.read',
        sortOrder: 50,
      },
      {
        key: 'activity',
        name: 'Actividad global',
        route: '/platform/actividad',
        permissionKey: 'platform.activity.read',
        sortOrder: 60,
      },
    ],
  },
  {
    key: 'dashboard',
    name: 'Inicio',
    icon: 'layout-dashboard',
    audience: 'ORGANIZATION',
    sortOrder: 10,
    submodules: [
      {
        key: 'home',
        name: 'Panel principal',
        route: '/dashboard',
        permissionKey: 'dashboard.read',
        sortOrder: 10,
      },
    ],
  },
  {
    key: 'settings',
    name: 'Configuracion',
    icon: 'settings',
    audience: 'ORGANIZATION',
    sortOrder: 90,
    submodules: [
      {
        key: 'organization',
        name: 'Empresa',
        route: '/configuracion/empresa',
        permissionKey: 'settings.organization.read',
        sortOrder: 10,
      },
      {
        key: 'branches',
        name: 'Sucursales',
        route: '/configuracion/sucursales',
        permissionKey: 'settings.branches.read',
        sortOrder: 20,
      },
      {
        key: 'dining-spaces',
        name: 'Areas y mesas',
        route: '/configuracion/salones-mesas',
        permissionKey: 'settings.tables.read',
        sortOrder: 25,
      },
      {
        key: 'users',
        name: 'Usuarios',
        route: '/configuracion/usuarios',
        permissionKey: 'settings.users.read',
        sortOrder: 30,
      },
      {
        key: 'roles',
        name: 'Roles',
        route: '/configuracion/roles',
        permissionKey: 'settings.roles.read',
        sortOrder: 40,
      },
      {
        key: 'parameters',
        name: 'Parametros',
        route: '/configuracion/parametros',
        permissionKey: 'settings.parameters.read',
        sortOrder: 50,
      },
      {
        key: 'payment-methods',
        name: 'Metodos de pago',
        route: '/configuracion/metodos-pago',
        permissionKey: 'settings.payment_methods.read',
        sortOrder: 55,
      },
      {
        key: 'printing',
        name: 'Dispositivos e impresion',
        route: '/configuracion/impresion',
        permissionKey: 'settings.printing.read',
        sortOrder: 60,
      },
    ],
  },
  {
    key: 'rrhh',
    name: 'Recursos humanos',
    icon: 'users',
    audience: 'ORGANIZATION',
    sortOrder: 100,
    submodules: [
      {
        key: 'collaborators',
        name: 'Colaboradores',
        route: '/rrhh/colaboradores',
        permissionKey: 'rrhh.collaborators.read',
        sortOrder: 10,
      },
      {
        key: 'attendance',
        name: 'Asistencia',
        route: '/rrhh/asistencia',
        permissionKey: 'rrhh.attendance.read',
        sortOrder: 20,
      },
      {
        key: 'payroll',
        name: 'Boletas de pago',
        route: '/rrhh/boletas-pago',
        permissionKey: 'rrhh.payroll.read',
        sortOrder: 30,
      },
    ],
  },
  {
    key: 'sales',
    name: 'Ventas',
    icon: 'shopping-bag',
    audience: 'ORGANIZATION',
    sortOrder: 40,
    submodules: [
      {
        key: 'customers',
        name: 'Clientes',
        route: '/ventas/clientes',
        permissionKey: 'sales.customers.read',
        sortOrder: 10,
      },
      {
        key: 'quotes',
        name: 'Cotizaciones',
        route: '/ventas/cotizaciones',
        permissionKey: 'sales.quotes.read',
        sortOrder: 20,
      },
      {
        key: 'orders',
        name: 'Pedidos',
        route: '/ventas/pedidos',
        permissionKey: 'sales.orders.read',
        sortOrder: 30,
      },
      {
        key: 'kitchen',
        name: 'Cocina',
        route: '/ventas/cocina',
        permissionKey: 'sales.kitchen.read',
        sortOrder: 35,
      },
      {
        key: 'pos',
        name: 'POS',
        route: '/ventas/pos',
        permissionKey: 'sales.pos.read',
        sortOrder: 40,
      },
    ],
  },
  {
    key: 'cash',
    name: 'Caja',
    icon: 'wallet',
    audience: 'ORGANIZATION',
    sortOrder: 30,
    submodules: [
      {
        key: 'openings',
        name: 'Apertura',
        route: '/caja/apertura',
        permissionKey: 'cash.openings.read',
        sortOrder: 10,
      },
      {
        key: 'movements',
        name: 'Movimientos',
        route: '/caja/movimientos',
        permissionKey: 'cash.movements.read',
        sortOrder: 20,
      },
      {
        key: 'closings',
        name: 'Cierre',
        route: '/caja/cierre',
        permissionKey: 'cash.closings.read',
        sortOrder: 30,
      },
    ],
  },
  {
    key: 'catalog',
    name: 'Catalogo',
    icon: 'package',
    audience: 'ORGANIZATION',
    sortOrder: 20,
    submodules: [
      {
        key: 'products',
        name: 'Productos',
        route: '/catalogo/productos',
        permissionKey: 'catalog.products.read',
        sortOrder: 10,
      },
      {
        key: 'categories',
        name: 'Categorias',
        route: '/catalogo/categorias',
        permissionKey: 'catalog.categories.read',
        sortOrder: 20,
      },
      {
        key: 'stock',
        name: 'Stock',
        route: '/catalogo/stock',
        permissionKey: 'catalog.stock.read',
        sortOrder: 30,
      },
      {
        key: 'adjustments',
        name: 'Ajustes',
        route: '/catalogo/ajustes',
        permissionKey: 'catalog.adjustments.read',
        sortOrder: 40,
      },
    ],
  },
  {
    key: 'finance',
    name: 'Finanzas',
    icon: 'finance',
    audience: 'ORGANIZATION',
    sortOrder: 70,
    submodules: [
      {
        key: 'billing-documents',
        name: 'Facturacion',
        route: '/finanzas/facturacion',
        permissionKey: 'billing.documents.read',
        sortOrder: 10,
      },
      {
        key: 'fiscal-series',
        name: 'Series fiscales',
        route: '/finanzas/series-fiscales',
        permissionKey: 'billing.series.read',
        sortOrder: 20,
      },
      {
        key: 'fiscal-providers',
        name: 'Proveedores fiscales',
        route: '/finanzas/proveedores-fiscales',
        permissionKey: 'billing.providers.read',
        sortOrder: 30,
      },
      {
        key: 'receivables',
        name: 'Cuentas por cobrar',
        route: '/finanzas/cuentas-por-cobrar',
        permissionKey: 'finance.receivables.read',
        sortOrder: 40,
      },
      {
        key: 'expenses',
        name: 'Gastos',
        route: '/finanzas/gastos',
        permissionKey: 'finance.expenses.read',
        sortOrder: 50,
      },
      {
        key: 'bank-reconciliation',
        name: 'Bancos y conciliacion',
        route: '/finanzas/bancos-conciliacion',
        permissionKey: 'finance.banks.read',
        sortOrder: 60,
      },
    ],
  },
  {
    key: 'reports',
    name: 'Reportes',
    icon: 'bar-chart-3',
    audience: 'ORGANIZATION',
    sortOrder: 80,
    submodules: [
      {
        key: 'sales',
        name: 'Ventas',
        route: '/reportes/ventas',
        permissionKey: 'reports.sales.read',
        sortOrder: 10,
      },
      {
        key: 'cash',
        name: 'Caja',
        route: '/reportes/caja',
        permissionKey: 'reports.cash.read',
        sortOrder: 20,
      },
      {
        key: 'inventory',
        name: 'Inventario',
        route: '/reportes/inventario',
        permissionKey: 'reports.inventory.read',
        sortOrder: 30,
      },
      {
        key: 'customers',
        name: 'Clientes',
        route: '/reportes/clientes',
        permissionKey: 'reports.customers.read',
        sortOrder: 40,
      },
    ],
  },
  {
    key: 'operations',
    name: 'Operaciones',
    icon: 'truck',
    audience: 'ORGANIZATION',
    sortOrder: 110,
    submodules: [
      {
        key: 'manifests',
        name: 'Manifiestos',
        route: '/manifiestos',
        permissionKey: 'operations.manifests.read',
        sortOrder: 10,
      },
      {
        key: 'carriers',
        name: 'Transportistas',
        route: '/transportistas',
        permissionKey: 'operations.carriers.read',
        sortOrder: 20,
      },
      {
        key: 'routes',
        name: 'Rutas',
        route: '/operaciones/rutas',
        permissionKey: 'operations.routes.read',
        sortOrder: 30,
      },
    ],
  },
];

export const permissions: PermissionSeed[] = [
  {
    key: 'platform.organizations.read',
    name: 'Ver organizaciones',
    description: 'Permite ver empresas cliente registradas en Kapos.',
    moduleKey: 'platform',
    submoduleKey: 'organizations',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.organizations.create',
    name: 'Crear organizaciones',
    description: 'Permite crear nuevas organizaciones cliente.',
    moduleKey: 'platform',
    submoduleKey: 'organizations',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.users.read',
    name: 'Ver usuarios globales',
    description: 'Permite revisar identidades globales de la plataforma.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.users.create',
    name: 'Crear usuarios globales',
    description: 'Permite registrar identidades globales manualmente.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.memberships.read',
    name: 'Ver memberships',
    description: 'Permite revisar relaciones entre usuarios y organizaciones.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.roles.read',
    name: 'Ver roles base',
    description:
      'Permite consultar roles maestros de plataforma y organizacion.',
    moduleKey: 'platform',
    submoduleKey: 'roles',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.permissions.read',
    name: 'Ver permisos maestros',
    description: 'Permite consultar el catalogo de permisos base.',
    moduleKey: 'platform',
    submoduleKey: 'permissions',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.modules.read',
    name: 'Ver modulos del sistema',
    description: 'Permite consultar modulos y submodulos sembrados en Kapos.',
    moduleKey: 'platform',
    submoduleKey: 'modules',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.activity.read',
    name: 'Ver actividad global',
    description: 'Permite consultar actividad global de clientes y accesos.',
    moduleKey: 'platform',
    submoduleKey: 'activity',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'dashboard.read',
    name: 'Ver dashboard',
    description: 'Permite ver el panel principal del ERP.',
    moduleKey: 'dashboard',
    submoduleKey: 'home',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.organization.read',
    name: 'Ver empresa',
    description: 'Permite consultar datos generales de la organizacion.',
    moduleKey: 'settings',
    submoduleKey: 'organization',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.branches.read',
    name: 'Ver sucursales',
    description: 'Permite revisar sucursales habilitadas.',
    moduleKey: 'settings',
    submoduleKey: 'branches',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.users.read',
    name: 'Ver usuarios',
    description: 'Permite listar usuarios internos de la organizacion.',
    moduleKey: 'settings',
    submoduleKey: 'users',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.users.create',
    name: 'Crear usuarios',
    description: 'Permite crear cuentas internas.',
    moduleKey: 'settings',
    submoduleKey: 'users',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.roles.read',
    name: 'Ver roles',
    description: 'Permite listar roles de la organizacion.',
    moduleKey: 'settings',
    submoduleKey: 'roles',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.roles.create',
    name: 'Crear roles',
    description: 'Permite crear roles internos.',
    moduleKey: 'settings',
    submoduleKey: 'roles',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.parameters.read',
    name: 'Ver parametros',
    description: 'Permite revisar parametros generales del ERP.',
    moduleKey: 'settings',
    submoduleKey: 'parameters',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.payment_methods.read',
    name: 'Ver metodos de pago',
    description: 'Permite revisar los metodos de pago usados por caja y POS.',
    moduleKey: 'settings',
    submoduleKey: 'payment-methods',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.printing.read',
    name: 'Ver dispositivos e impresion',
    description: 'Permite revisar impresoras, formatos y reglas de impresion.',
    moduleKey: 'settings',
    submoduleKey: 'printing',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'rrhh.collaborators.read',
    name: 'Ver colaboradores',
    description: 'Permite listar colaboradores de la organizacion.',
    moduleKey: 'rrhh',
    submoduleKey: 'collaborators',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'rrhh.collaborators.create',
    name: 'Crear colaboradores',
    description: 'Permite registrar nuevos colaboradores.',
    moduleKey: 'rrhh',
    submoduleKey: 'collaborators',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'rrhh.collaborators.update',
    name: 'Editar colaboradores',
    description: 'Permite actualizar datos de colaboradores.',
    moduleKey: 'rrhh',
    submoduleKey: 'collaborators',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'rrhh.attendance.read',
    name: 'Ver asistencia',
    description: 'Permite revisar asistencia por sede.',
    moduleKey: 'rrhh',
    submoduleKey: 'attendance',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'rrhh.payroll.read',
    name: 'Ver boletas',
    description: 'Permite revisar boletas y planillas.',
    moduleKey: 'rrhh',
    submoduleKey: 'payroll',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.customers.read',
    name: 'Ver clientes',
    description: 'Permite consultar clientes comerciales.',
    moduleKey: 'sales',
    submoduleKey: 'customers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.customers.create',
    name: 'Crear clientes',
    description: 'Permite registrar nuevos clientes.',
    moduleKey: 'sales',
    submoduleKey: 'customers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.quotes.read',
    name: 'Ver cotizaciones',
    description: 'Permite revisar cotizaciones.',
    moduleKey: 'sales',
    submoduleKey: 'quotes',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.quotes.create',
    name: 'Crear cotizaciones',
    description: 'Permite emitir cotizaciones.',
    moduleKey: 'sales',
    submoduleKey: 'quotes',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.read',
    name: 'Ver pedidos',
    description: 'Permite consultar pedidos.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.create',
    name: 'Crear pedidos',
    description: 'Permite registrar pedidos.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.pos.read',
    name: 'Ver POS',
    description: 'Permite usar o revisar el punto de venta.',
    moduleKey: 'sales',
    submoduleKey: 'pos',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.pos.create',
    name: 'Crear ventas POS',
    description: 'Permite registrar ventas pagadas desde POS web o mobile.',
    moduleKey: 'sales',
    submoduleKey: 'pos',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.openings.read',
    name: 'Ver aperturas de caja',
    description: 'Permite consultar aperturas de caja.',
    moduleKey: 'cash',
    submoduleKey: 'openings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.movements.read',
    name: 'Ver movimientos de caja',
    description: 'Permite consultar ingresos y salidas de caja.',
    moduleKey: 'cash',
    submoduleKey: 'movements',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.closings.read',
    name: 'Ver cierres de caja',
    description: 'Permite consultar cierres de caja.',
    moduleKey: 'cash',
    submoduleKey: 'closings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.products.read',
    name: 'Ver productos',
    description: 'Permite listar productos e insumos.',
    moduleKey: 'catalog',
    submoduleKey: 'products',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.categories.read',
    name: 'Ver categorias',
    description: 'Permite revisar categorias del catalogo.',
    moduleKey: 'catalog',
    submoduleKey: 'categories',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.stock.read',
    name: 'Ver stock',
    description: 'Permite consultar stock por organizacion o sede.',
    moduleKey: 'catalog',
    submoduleKey: 'stock',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.read',
    name: 'Ver ajustes de stock',
    description: 'Permite consultar ajustes de stock.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.documents.read',
    name: 'Ver documentos',
    description: 'Permite revisar documentos emitidos.',
    moduleKey: 'finance',
    submoduleKey: 'billing-documents',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.documents.issue',
    name: 'Emitir documentos',
    description: 'Permite emitir o reintentar boletas y facturas electronicas.',
    moduleKey: 'finance',
    submoduleKey: 'billing-documents',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.documents.print',
    name: 'Imprimir documentos',
    description: 'Permite abrir comprobantes fiscales para impresion o reimpresion.',
    moduleKey: 'finance',
    submoduleKey: 'billing-documents',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.series.read',
    name: 'Ver series',
    description: 'Permite revisar series y correlativos.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-series',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.series.create',
    name: 'Crear series',
    description: 'Permite crear series y correlativos por sucursal.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-series',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.series.update',
    name: 'Editar series',
    description: 'Permite editar series, estado y proximo correlativo.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-series',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.series.delete',
    name: 'Eliminar series',
    description: 'Permite eliminar series sin comprobantes asociados.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-series',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.providers.read',
    name: 'Ver integraciones de facturacion',
    description: 'Permite revisar integraciones de facturacion.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-providers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.providers.create',
    name: 'Crear integraciones de facturacion',
    description: 'Permite registrar credenciales y conexion del proveedor fiscal.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-providers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.providers.update',
    name: 'Editar integraciones de facturacion',
    description: 'Permite editar credenciales y conexion del proveedor fiscal.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-providers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.providers.activate',
    name: 'Activar integraciones de facturacion',
    description: 'Permite activar la emision electronica.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-providers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.providers.deactivate',
    name: 'Desactivar integraciones de facturacion',
    description: 'Permite pausar la emision electronica sin borrar credenciales.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-providers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'billing.providers.delete',
    name: 'Eliminar integraciones de facturacion',
    description: 'Permite eliminar credenciales del proveedor fiscal.',
    moduleKey: 'finance',
    submoduleKey: 'fiscal-providers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'finance.receivables.read',
    name: 'Ver cuentas por cobrar',
    description: 'Permite revisar ventas pendientes y saldos por cobrar.',
    moduleKey: 'finance',
    submoduleKey: 'receivables',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'finance.expenses.read',
    name: 'Ver gastos',
    description: 'Permite revisar gastos administrativos y operativos.',
    moduleKey: 'finance',
    submoduleKey: 'expenses',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'finance.banks.read',
    name: 'Ver bancos y conciliacion',
    description: 'Permite revisar bancos, depositos y conciliacion financiera.',
    moduleKey: 'finance',
    submoduleKey: 'bank-reconciliation',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'reports.sales.read',
    name: 'Ver reportes de ventas',
    description: 'Permite consultar reportes de ventas.',
    moduleKey: 'reports',
    submoduleKey: 'sales',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'reports.cash.read',
    name: 'Ver reportes de caja',
    description: 'Permite consultar reportes de caja.',
    moduleKey: 'reports',
    submoduleKey: 'cash',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'reports.inventory.read',
    name: 'Ver reportes de inventario',
    description: 'Permite consultar reportes de inventario.',
    moduleKey: 'reports',
    submoduleKey: 'inventory',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'reports.customers.read',
    name: 'Ver reportes de clientes',
    description: 'Permite consultar reportes de clientes.',
    moduleKey: 'reports',
    submoduleKey: 'customers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'operations.manifests.read',
    name: 'Ver manifiestos',
    description: 'Permite consultar manifiestos operativos.',
    moduleKey: 'operations',
    submoduleKey: 'manifests',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'operations.carriers.read',
    name: 'Ver transportistas',
    description: 'Permite listar transportistas.',
    moduleKey: 'operations',
    submoduleKey: 'carriers',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'operations.routes.read',
    name: 'Ver rutas',
    description: 'Permite consultar rutas operativas.',
    moduleKey: 'operations',
    submoduleKey: 'routes',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
];

export const obsoletePermissionKeys = [
  'platform.organizations.manage',
  'platform.users.manage',
  'platform.memberships.manage',
  'platform.roles.manage',
  'platform.permissions.manage',
  'platform.modules.manage',
  'settings.organization.manage',
  'settings.branches.manage',
  'settings.users.assign_roles',
  'settings.roles.manage_permissions',
  'settings.parameters.manage',
  'cash.openings.manage',
  'cash.movements.manage',
  'cash.closings.manage',
  'catalog.products.manage',
  'catalog.categories.manage',
  'catalog.adjustments.manage',
  'inventory.products.manage',
  'inventory.categories.manage',
  'inventory.adjustments.manage',
  'billing.documents.manage',
  'billing.series.manage',
  'billing.series.configure',
  'billing.providers.configure',
  'finance.billing.read',
  'finance.treasury.read',
  'finance.reports.read',
];

export const obsoleteModuleKeys = ['billing'];

permissions.push(
  {
    key: 'settings.tables.read',
    name: 'Ver areas y mesas',
    description:
      'Permite consultar la distribucion operativa de cada sucursal.',
    moduleKey: 'settings',
    submoduleKey: 'dining-spaces',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.tables.create',
    name: 'Crear areas y mesas',
    description: 'Permite configurar areas y mesas por sucursal.',
    moduleKey: 'settings',
    submoduleKey: 'dining-spaces',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.tables.update',
    name: 'Actualizar areas y mesas',
    description: 'Permite editar o desactivar areas y mesas.',
    moduleKey: 'settings',
    submoduleKey: 'dining-spaces',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.update',
    name: 'Actualizar cuentas abiertas',
    description: 'Permite agregar productos y actualizar pedidos abiertos.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.send_kitchen',
    name: 'Enviar comandas',
    description: 'Permite enviar productos de una cuenta a cocina o barra.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.update_kitchen',
    name: 'Actualizar comandas',
    description: 'Permite cambiar el estado de preparacion de una comanda.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.pay',
    name: 'Cobrar cuentas',
    description:
      'Permite registrar pagos parciales o totales de cuentas abiertas.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.cancel',
    name: 'Cancelar cuentas',
    description: 'Permite cancelar cuentas abiertas que aun no tengan pagos.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.move_table',
    name: 'Trasladar y unir mesas',
    description: 'Permite trasladar una cuenta y anexar mesas libres.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.prebill',
    name: 'Generar precuentas',
    description: 'Permite generar e imprimir una precuenta sin cerrar la venta.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.orders.cancel_item',
    name: 'Anular productos de una cuenta',
    description: 'Permite anular productos con motivo y liberar su stock reservado.',
    moduleKey: 'sales',
    submoduleKey: 'orders',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.kitchen.read',
    name: 'Ver monitor de cocina',
    description: 'Permite consultar las comandas activas de cocina y barra.',
    moduleKey: 'sales',
    submoduleKey: 'kitchen',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'sales.pos.cancel',
    name: 'Anular ventas POS',
    description:
      'Permite anular ventas y reversar caja, stock, puntos y documento.',
    moduleKey: 'sales',
    submoduleKey: 'pos',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'platform.organizations.update',
    name: 'Actualizar organizaciones',
    description:
      'Permite editar datos, modulos y estado de organizaciones cliente.',
    moduleKey: 'platform',
    submoduleKey: 'organizations',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.organizations.activate',
    name: 'Activar organizaciones',
    description: 'Permite reactivar organizaciones suspendidas.',
    moduleKey: 'platform',
    submoduleKey: 'organizations',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.users.update',
    name: 'Actualizar usuarios globales',
    description: 'Permite editar identidad, estado y acceso de plataforma.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.users.activate',
    name: 'Activar usuarios globales',
    description: 'Permite reactivar usuarios globales.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.memberships.update',
    name: 'Actualizar memberships',
    description:
      'Permite vincular usuarios a organizaciones y editar sus accesos.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.memberships.delete',
    name: 'Eliminar memberships',
    description: 'Permite desvincular usuarios de organizaciones.',
    moduleKey: 'platform',
    submoduleKey: 'global-users',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.roles.create',
    name: 'Crear roles base',
    description: 'Permite crear roles base o roles desde plataforma.',
    moduleKey: 'platform',
    submoduleKey: 'roles',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.roles.update',
    name: 'Actualizar roles base',
    description: 'Permite editar roles base del sistema.',
    moduleKey: 'platform',
    submoduleKey: 'roles',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.permissions.create',
    name: 'Crear permisos maestros',
    description: 'Permite registrar permisos base del sistema.',
    moduleKey: 'platform',
    submoduleKey: 'permissions',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.permissions.update',
    name: 'Actualizar permisos maestros',
    description: 'Permite editar permisos base del sistema.',
    moduleKey: 'platform',
    submoduleKey: 'permissions',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.modules.create',
    name: 'Crear modulos del sistema',
    description: 'Permite crear modulos y submodulos base.',
    moduleKey: 'platform',
    submoduleKey: 'modules',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'platform.modules.update',
    name: 'Actualizar modulos del sistema',
    description: 'Permite editar modulos y submodulos base.',
    moduleKey: 'platform',
    submoduleKey: 'modules',
    scope: 'PLATFORM',
    audience: 'PLATFORM',
  },
  {
    key: 'settings.organization.update',
    name: 'Actualizar empresa',
    description: 'Permite editar datos base de la organizacion.',
    moduleKey: 'settings',
    submoduleKey: 'organization',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.branches.create',
    name: 'Crear sucursales',
    description: 'Permite crear nuevas sucursales.',
    moduleKey: 'settings',
    submoduleKey: 'branches',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.branches.update',
    name: 'Actualizar sucursales',
    description: 'Permite editar o desactivar sucursales.',
    moduleKey: 'settings',
    submoduleKey: 'branches',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.branches.activate',
    name: 'Activar sucursales',
    description: 'Permite reactivar sucursales.',
    moduleKey: 'settings',
    submoduleKey: 'branches',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.users.update',
    name: 'Actualizar usuarios',
    description:
      'Permite editar usuarios internos, roles y permisos delegables.',
    moduleKey: 'settings',
    submoduleKey: 'users',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.users.activate',
    name: 'Activar usuarios',
    description: 'Permite reactivar usuarios internos suspendidos.',
    moduleKey: 'settings',
    submoduleKey: 'users',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.roles.update',
    name: 'Actualizar roles',
    description: 'Permite editar permisos de roles internos.',
    moduleKey: 'settings',
    submoduleKey: 'roles',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.roles.delete',
    name: 'Eliminar roles',
    description: 'Permite archivar roles personalizados.',
    moduleKey: 'settings',
    submoduleKey: 'roles',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.parameters.create',
    name: 'Crear parametros',
    description: 'Permite crear parametros operativos.',
    moduleKey: 'settings',
    submoduleKey: 'parameters',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.parameters.update',
    name: 'Actualizar parametros',
    description: 'Permite editar o desactivar parametros operativos.',
    moduleKey: 'settings',
    submoduleKey: 'parameters',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.parameters.activate',
    name: 'Activar parametros',
    description: 'Permite reactivar parametros operativos.',
    moduleKey: 'settings',
    submoduleKey: 'parameters',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.payment_methods.create',
    name: 'Crear metodos de pago',
    description: 'Permite crear metodos de pago para caja y POS.',
    moduleKey: 'settings',
    submoduleKey: 'payment-methods',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.payment_methods.update',
    name: 'Actualizar metodos de pago',
    description: 'Permite editar datos y estado de metodos de pago.',
    moduleKey: 'settings',
    submoduleKey: 'payment-methods',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.payment_methods.activate',
    name: 'Activar metodos de pago',
    description: 'Permite reactivar metodos de pago deshabilitados.',
    moduleKey: 'settings',
    submoduleKey: 'payment-methods',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.payment_methods.delete',
    name: 'Eliminar metodos de pago',
    description: 'Permite eliminar metodos de pago sin operaciones asociadas.',
    moduleKey: 'settings',
    submoduleKey: 'payment-methods',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.printing.create',
    name: 'Crear dispositivos de impresion',
    description: 'Permite registrar impresoras y estaciones de impresion.',
    moduleKey: 'settings',
    submoduleKey: 'printing',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.printing.update',
    name: 'Actualizar dispositivos de impresion',
    description: 'Permite editar impresoras, formatos y reglas de impresion.',
    moduleKey: 'settings',
    submoduleKey: 'printing',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'settings.printing.activate',
    name: 'Activar dispositivos de impresion',
    description: 'Permite activar o pausar rutas de impresion.',
    moduleKey: 'settings',
    submoduleKey: 'printing',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.openings.create',
    name: 'Crear aperturas de caja',
    description: 'Permite crear cajas y abrir sesiones de caja.',
    moduleKey: 'cash',
    submoduleKey: 'openings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.openings.update',
    name: 'Actualizar aperturas de caja',
    description: 'Permite editar cajas y desactivar registros de caja.',
    moduleKey: 'cash',
    submoduleKey: 'openings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.openings.activate',
    name: 'Activar aperturas de caja',
    description: 'Permite reactivar cajas desactivadas.',
    moduleKey: 'cash',
    submoduleKey: 'openings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.movements.create',
    name: 'Crear movimientos de caja',
    description: 'Permite registrar ingresos, egresos y retiros de caja.',
    moduleKey: 'cash',
    submoduleKey: 'movements',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.movements.cancel',
    name: 'Cancelar movimientos de caja',
    description: 'Permite anular movimientos de caja cuando exista el flujo.',
    moduleKey: 'cash',
    submoduleKey: 'movements',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.closings.create',
    name: 'Crear cierres de caja',
    description: 'Permite cerrar sesiones de caja.',
    moduleKey: 'cash',
    submoduleKey: 'closings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.closings.approve',
    name: 'Aprobar cierres de caja',
    description: 'Permite aprobar diferencias de cierre.',
    moduleKey: 'cash',
    submoduleKey: 'closings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.closings.reject',
    name: 'Rechazar cierres de caja',
    description: 'Permite rechazar cierres observados.',
    moduleKey: 'cash',
    submoduleKey: 'closings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'cash.closings.cancel',
    name: 'Cancelar cierres de caja',
    description: 'Permite cancelar cierres cuando exista el flujo.',
    moduleKey: 'cash',
    submoduleKey: 'closings',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.products.create',
    name: 'Crear productos',
    description: 'Permite crear productos e insumos.',
    moduleKey: 'catalog',
    submoduleKey: 'products',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.products.update',
    name: 'Actualizar productos',
    description: 'Permite editar o desactivar productos e insumos.',
    moduleKey: 'catalog',
    submoduleKey: 'products',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.products.delete',
    name: 'Eliminar productos',
    description: 'Permite eliminar productos cuando no comprometa historial.',
    moduleKey: 'catalog',
    submoduleKey: 'products',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.products.activate',
    name: 'Activar productos',
    description: 'Permite reactivar productos desactivados.',
    moduleKey: 'catalog',
    submoduleKey: 'products',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.products.export',
    name: 'Exportar productos',
    description: 'Permite exportar listados de productos.',
    moduleKey: 'catalog',
    submoduleKey: 'products',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.categories.create',
    name: 'Crear categorias',
    description: 'Permite crear categorias del catalogo.',
    moduleKey: 'catalog',
    submoduleKey: 'categories',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.categories.update',
    name: 'Actualizar categorias',
    description: 'Permite editar o desactivar categorias.',
    moduleKey: 'catalog',
    submoduleKey: 'categories',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.categories.delete',
    name: 'Eliminar categorias',
    description: 'Permite eliminar categorias cuando no comprometa historial.',
    moduleKey: 'catalog',
    submoduleKey: 'categories',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.categories.activate',
    name: 'Activar categorias',
    description: 'Permite reactivar categorias desactivadas.',
    moduleKey: 'catalog',
    submoduleKey: 'categories',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.categories.export',
    name: 'Exportar categorias',
    description: 'Permite exportar listados de categorias.',
    moduleKey: 'catalog',
    submoduleKey: 'categories',
    scope: 'ORGANIZATION',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.stock.update',
    name: 'Actualizar stock',
    description: 'Permite actualizar stock inicial o correcciones simples.',
    moduleKey: 'catalog',
    submoduleKey: 'stock',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.stock.export',
    name: 'Exportar stock',
    description: 'Permite exportar existencias de stock.',
    moduleKey: 'catalog',
    submoduleKey: 'stock',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.create',
    name: 'Crear ajustes de stock',
    description: 'Permite crear ajustes de catalogo y stock.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.update',
    name: 'Actualizar ajustes de stock',
    description: 'Permite editar ajustes de stock pendientes.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.approve',
    name: 'Aprobar ajustes de stock',
    description: 'Permite aprobar ajustes de stock.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.reject',
    name: 'Rechazar ajustes de stock',
    description: 'Permite rechazar ajustes de stock.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.cancel',
    name: 'Cancelar ajustes de stock',
    description: 'Permite anular ajustes de stock.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
  {
    key: 'catalog.adjustments.export',
    name: 'Exportar ajustes de stock',
    description: 'Permite exportar ajustes de stock.',
    moduleKey: 'catalog',
    submoduleKey: 'adjustments',
    scope: 'BRANCH',
    audience: 'ORGANIZATION',
  },
);

function isActivePermission(permission: PermissionSeed) {
  return !obsoletePermissionKeys.includes(permission.key);
}

export const roles: RoleSeed[] = [
  {
    context: 'PLATFORM',
    scopeKey: 'platform:platform.super_admin',
    key: 'platform.super_admin',
    name: 'Superadmin de plataforma',
    description:
      'Acceso completo a clientes, catalogos base y actividad global de Kapos.',
    isSystem: true,
    permissionKeys: permissions
      .filter(
        (permission) =>
          permission.audience === 'PLATFORM' && isActivePermission(permission),
      )
      .map((permission) => permission.key),
  },
  {
    context: 'PLATFORM',
    scopeKey: 'platform:platform.assistant',
    key: 'platform.assistant',
    name: 'Asistente de plataforma',
    description:
      'Apoya al superadmin con lectura operativa y tareas delegadas sin control absoluto de Kapos.',
    isSystem: true,
    permissionKeys: [
      'platform.organizations.read',
      'platform.users.read',
      'platform.memberships.read',
      'platform.roles.read',
      'platform.permissions.read',
      'platform.modules.read',
      'platform.activity.read',
    ],
  },
  {
    context: 'ORGANIZATION',
    scopeKey: 'system:organization.owner',
    key: 'organization.owner',
    name: 'Owner de organizacion',
    description: 'Maximo responsable del cliente dentro de Kapos.',
    isSystem: true,
    permissionKeys: permissions
      .filter(
        (permission) =>
          permission.audience === 'ORGANIZATION' &&
          isActivePermission(permission),
      )
      .map((permission) => permission.key),
  },
  {
    context: 'ORGANIZATION',
    scopeKey: 'system:organization.admin',
    key: 'organization.admin',
    name: 'Administrador de organizacion',
    description:
      'Gestiona usuarios internos, configuracion y operacion general.',
    isSystem: true,
    permissionKeys: [
      'dashboard.read',
      'settings.organization.read',
      'settings.organization.update',
      'settings.branches.read',
      'settings.branches.create',
      'settings.branches.update',
      'settings.branches.activate',
      'settings.tables.read',
      'settings.tables.create',
      'settings.tables.update',
      'settings.users.read',
      'settings.users.create',
      'settings.users.update',
      'settings.users.activate',
      'settings.roles.read',
      'settings.roles.create',
      'settings.roles.update',
      'settings.roles.delete',
      'settings.parameters.read',
      'settings.parameters.create',
      'settings.parameters.update',
      'settings.parameters.activate',
      'settings.payment_methods.read',
      'settings.payment_methods.create',
      'settings.payment_methods.update',
      'settings.payment_methods.activate',
      'settings.payment_methods.delete',
      'settings.printing.read',
      'settings.printing.create',
      'settings.printing.update',
      'settings.printing.activate',
      'rrhh.collaborators.read',
      'rrhh.collaborators.create',
      'rrhh.collaborators.update',
      'rrhh.attendance.read',
      'rrhh.payroll.read',
      'sales.customers.read',
      'sales.customers.create',
      'sales.quotes.read',
      'sales.quotes.create',
      'sales.orders.read',
      'sales.orders.create',
      'sales.orders.update',
      'sales.orders.send_kitchen',
      'sales.orders.update_kitchen',
      'sales.orders.pay',
      'sales.orders.cancel',
      'sales.orders.move_table',
      'sales.orders.prebill',
      'sales.orders.cancel_item',
      'sales.kitchen.read',
      'sales.pos.read',
      'sales.pos.create',
      'sales.pos.cancel',
      'cash.openings.read',
      'cash.openings.create',
      'cash.openings.update',
      'cash.openings.activate',
      'cash.movements.read',
      'cash.movements.create',
      'cash.movements.cancel',
      'cash.closings.read',
      'cash.closings.create',
      'cash.closings.approve',
      'cash.closings.reject',
      'cash.closings.cancel',
      'catalog.products.read',
      'catalog.products.create',
      'catalog.products.update',
      'catalog.products.delete',
      'catalog.products.activate',
      'catalog.products.export',
      'catalog.categories.read',
      'catalog.categories.create',
      'catalog.categories.update',
      'catalog.categories.delete',
      'catalog.categories.activate',
      'catalog.categories.export',
      'catalog.stock.read',
      'catalog.stock.update',
      'catalog.stock.export',
      'catalog.adjustments.read',
      'catalog.adjustments.create',
      'catalog.adjustments.update',
      'catalog.adjustments.approve',
      'catalog.adjustments.reject',
      'catalog.adjustments.cancel',
      'catalog.adjustments.export',
      'billing.documents.read',
      'billing.documents.issue',
      'billing.documents.print',
      'billing.series.read',
      'billing.series.create',
      'billing.series.update',
      'billing.series.delete',
      'billing.providers.read',
      'billing.providers.create',
      'billing.providers.update',
      'billing.providers.activate',
      'billing.providers.deactivate',
      'billing.providers.delete',
      'finance.receivables.read',
      'finance.expenses.read',
      'finance.banks.read',
      'reports.sales.read',
      'reports.cash.read',
      'reports.inventory.read',
      'reports.customers.read',
      'operations.manifests.read',
      'operations.carriers.read',
      'operations.routes.read',
    ],
  },
  {
    context: 'ORGANIZATION',
    scopeKey: 'system:organization.supervisor',
    key: 'organization.supervisor',
    name: 'Supervisor',
    description:
      'Controla operacion diaria y revisa resultados sin dominio total del sistema.',
    isSystem: true,
    permissionKeys: [
      'dashboard.read',
      'rrhh.collaborators.read',
      'rrhh.attendance.read',
      'settings.tables.read',
      'settings.payment_methods.read',
      'sales.customers.read',
      'sales.quotes.read',
      'sales.orders.read',
      'sales.orders.create',
      'sales.orders.update',
      'sales.orders.send_kitchen',
      'sales.orders.update_kitchen',
      'sales.orders.pay',
      'sales.orders.move_table',
      'sales.orders.prebill',
      'sales.orders.cancel_item',
      'sales.kitchen.read',
      'sales.pos.read',
      'sales.pos.create',
      'sales.pos.cancel',
      'cash.openings.read',
      'cash.movements.read',
      'cash.closings.read',
      'catalog.products.read',
      'catalog.categories.read',
      'catalog.stock.read',
      'billing.documents.read',
      'billing.documents.print',
      'reports.sales.read',
      'reports.cash.read',
      'operations.manifests.read',
      'operations.routes.read',
    ],
  },
  {
    context: 'ORGANIZATION',
    scopeKey: 'system:organization.cashier',
    key: 'organization.cashier',
    name: 'Cajero u operador base',
    description: 'Rol operativo para caja, pedidos y POS con alcance limitado.',
    isSystem: true,
    permissionKeys: [
      'dashboard.read',
      'settings.tables.read',
      'settings.payment_methods.read',
      'sales.customers.read',
      'sales.orders.read',
      'sales.orders.create',
      'sales.orders.update',
      'sales.orders.send_kitchen',
      'sales.orders.update_kitchen',
      'sales.orders.pay',
      'sales.orders.move_table',
      'sales.orders.prebill',
      'sales.kitchen.read',
      'sales.pos.read',
      'sales.pos.create',
      'cash.openings.read',
      'cash.openings.create',
      'cash.movements.read',
      'cash.movements.create',
      'cash.closings.read',
      'cash.closings.create',
      'billing.documents.read',
      'billing.documents.issue',
      'billing.documents.print',
    ],
  },
];
